import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LE ART - Profile 2024',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          'bg-gradient-to-b from-stone-100 to-stone-200 '
        )}
      >
        <Navbar />
        <main className="min-h-screen overflow-hidden">{children}</main>
      </body>
    </html>
  )
}
